name: LXScriptTreeExecutor
version: '${project.version}'
main: net.itsrelizc.mcserver.lxscripttreeexecutor.LXScriptTreeExecutor
api-version: '1.20'
commands:
  enteride:
    description: enters the ide state
    usage: /enteride