name: SFN
main: net.saltyfishstudios.bungee.Main
version: 1.0.0
author: Relizc
commands:
   message:
      description: command
      aliases: [m, w, whisper, dm, pm, tell, t]
      usage: §cInvalid usage! /message <player> <message>
   rank:
      description: command
      aliases: [r, rankup]
      usage: §cInvalid usage! /rank <player> <rankInt>
   test:
      description: test
      usage: /test
permissions:
    main.player:
       description: player
       default: true
    main.admin:
       description: admin
       default: op
   