name: RSLifeSteal
main: net.itsrelizc.lifesteal.waiting.Main
version: 1.0.0
author: Relizc
api-version: 1.19
depend: [NoteBlockAPI]
permissions:
    main.player:
       description: player
       default: true
    main.admin:
       description: admin
       default: op
      