name: LXScriptTreeExecutor
version: '1.0-SNAPSHOT'
main: net.itsrelizc.mcserver.lxscripttreeexecutor.LXScriptTreeExecutor
api-version: '1.20'
commands:
  enteride:
    description: enters the ide state
    usage: /enteride